version: '3.1'

services:
  my-app:
    build:
      context: ./my-app
      dockerfile: Dockerfile 
    ports:
      - "8080:80"  
    volumes:
      - ./files:/var/www/html/files:z
      
  elevenlabs-service:
    env_file:
      - .env
    volumes:
      - ./files:/elevenlabs-service/files:z
    build:
      context: ./elevenlabs-service
      dockerfile: Dockerfile
      
  downloaded-videos:
    volumes:
      - ./files:/downloaded-videos/files:z
    build:
      context: ./downloaded-videos
      dockerfile: Dockerfile

  subtitles:
    volumes:
      - ./files:/subtitles/files:z
    build:
      context: ./subtitles
      dockerfile: Dockerfile
    tty: true