version: '3.1'

services:
  my-app:
    build:
      context: ./my-app
      dockerfile: Dockerfile 
    ports:
      - "8080:80"  
      
  elevenlabs-service:
    env_file:
      - .env
    volumes:
      - ./files/scripts:/app/scripts
      - ./files/videos:/app/videos
      - ./files/videos_and_sound:/app/videos_and_sound
      - ./files/audios:/app/audios
    build:
      context: ./elevenlabs-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
      
  downloaded-videos:
    volumes:
      - ./files/videos:/downloaded-videos/videos:z
    build:
      context: ./downloaded-videos
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  auto-subtitle:
    volumes:
      - ./videos:/app/videos
    build:
      context: ./auto-subtitle
      dockerfile: Dockerfile
      
  script-generator:
    build:
      context: ./script-generator
      dockerfile: Dockerfile
