version: '3.1'

services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
      
  elevenlabs-service:
    env_file:
      - .env
    volumes:
      - .files/scripts:/app/scripts
      - .files/videos:/app/videos
      - .files/videos_and_sound:/app/videos_and_sound
      - .files/audios:/app/audios
    build:
      context: .
      dockerfile: Dockerfile.elevenlabs-service
    ports:
      - "5002:5002"
      
  downloaded-videos:
    volumes:
      - ./videos:/app/videos
    build:
      context: .
      dockerfile: Dockerfile.downloaded-videos
    ports:
      - "5001:5001"

  auto-subtitle:
    volumes:
      - ./videos:/app/videos
    build:
      context: .
      dockerfile: Dockerfile.auto-subtitle
      
  script-generator:
    build:
      context: .
      dockerfile: Dockerfile.script-generator
